name: Build Windows Meld (Simplified)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-python
          mingw-w64-x86_64-python-gobject
          mingw-w64-x86_64-python-cairo
          mingw-w64-x86_64-gtk3
          mingw-w64-x86_64-gtksourceview4
          mingw-w64-x86_64-adwaita-icon-theme
          mingw-w64-x86_64-meson
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gettext
          mingw-w64-x86_64-itstool
    
    - name: Configure and Build
      shell: msys2 {0}
      run: |
        # 配置时禁用帮助文档（避免 itstool 错误）
        meson setup _build \
          --prefix=/mingw64 \
          -Dprofile=Devel \
          -Dhelp=false
        
        # 构建
        ninja -C _build
        
        # 安装
        ninja -C _build install
    
    - name: Package
      shell: msys2 {0}
      run: |
        # 创建发布目录
        mkdir -p release/meld-windows
        
        # 复制 Meld
        cp -r /mingw64/bin/meld* release/meld-windows/
        cp -r /mingw64/share/meld release/meld-windows/
        
        # 创建便携版
        cd release
        tar -czf meld-windows-portable.tar.gz meld-windows/
        
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: meld-windows-build
        path: |
          release/*.tar.gz
          _build/
